# Generated by Django 4.1.1 on 2022-09-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='author',
            new_name='Автор',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='created_at',
            new_name='Время создания',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='heading',
            new_name='Заголовок',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='image',
            new_name='Картинка',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='content',
            new_name='Контент',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='title',
            new_name='Название',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='url',
            new_name='Название для url ссылки',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='description',
            new_name='Описание',
        ),
    ]
