# Generated by Django 4.1.1 on 2022-09-23 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog_app", "0004_alter_postmodel_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postmodel",
            old_name="created_at",
            new_name="created_data",
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="heading",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
