# Generated by Django 4.1.1 on 2022-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_postmodel_tag_commentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="text",
            field=models.TextField(verbose_name="Текст комментария"),
        ),
    ]
