# Generated by Django 4.1.1 on 2022-09-30 20:39

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog_app", "0007_alter_commentmodel_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Контент поста"
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="created_data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="heading",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="url",
            field=models.SlugField(verbose_name="Имя ссылки на ваш пост"),
        ),
    ]
